spring:
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: ${port:8900}
  
product-service:
  ribbon:
    listOfServers: http://localhost:8800, http://localhost:8801