spring:
  application:
    name: ecommerce-spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vahapgencdal/e-commerce-variables-repo.git
    
server:
  port: ${port:8888}